version: '3.8'

services:
  db:
    image: mariadb:11.1.1-rc-jammy
    container_name: sec0-backend-db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./data/db-aux0/additional-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=default ##REPLACE::ROOT_PASSWORD
      - MYSQL_DATABASE=default
  
  ## A container to host the frontend...
